### ISSUE TITLE
website

### ISSUE THREAD

**Issue by bradfodley** [leonv024/dbpwn#1]
can i search for a particular website database with this? if yes how

**Comment by leonv024** [comment]
no.

**Comment by bradfodley** [comment]
okay, am using torgurad vpn on my system but no database is found, how can i setup proxychains on windows?

**Comment by leonv024** [comment]
It’s out-dated and no longer works for me either. I’ll archive it and keep it as an example. You can search GHDB for dorks to find DB’s, if you don’t know how.
